name: build
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm ci
          npm run build
          npm run test

      - name: Lint
        run: |
          npm ci
          npm run build
          npm run lint
